# Generated by Django 5.1.7 on 2025-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentdetectionapp', '0002_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
